version: '3.4'

services:
  twitter-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=mongo
      - MONGO_HOSTNAME=mongo-db
      - MONGO_PORT=27017
      - MONGO_DB=twitter
    depends_on:
      - mongo-db
    ports:
      - 6000:8080

  mongo-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - 27017:27017